version: "3.9"
services:
  db:
    container_name: db
    image: mysql:8.0
    # command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=db
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=user_name
      - MYSQL_PASSWORD=password
    ports:
      - '3306:3306'
      
  web:
    container_name: web
    build: .
    volumes:
      - .:/rails_app
    ports:
      - "3002:3002"
    depends_on:
      - db
    stdin_open: true
    tty: true
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3002 -b '0.0.0.0'"
    # command: bash -c "cd todo_app && rails s -b '0.0.0.0'"

  phpmyadmin:
    container_name: phpmyadmin_host
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    ports:
      - "9999:80"
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=password

volumes:
  mysql-data:
    driver: local
